blueprint: file

title: Image

accept:
  type: image
  extension: jpg, png, jpeg
  mime: image/jpeg, image/png

columns:
  - width: 1/1
    sections:
      meta:
        type: fields
        fields:
          title:
            label: Titre
            type: text
            width: 1/2
          credit:
            label: Crédits
            type: text
            width: 1/2
          textColor:
            label: Couleur du texte sur l'image
            type: radio
            options:
              - white
              - black
            default: 1
            required: true
            width: 1/3
          showTitle:
            label: Afficher le titre de l'image
            type: toggle
            text:
              - ne pas afficher
              - afficher
            default: 0
            width: 1/3
