blueprint: page

title: About

icon: ☎️

options:
  changeSlug: false
  delete: false
  changeTitle: true
  sort: false
  changeStatus: false
  duplicate: false

tabs:
  content:
    icon: text
    label: À Propos
    fields:
      textAbout:
        label: Texte
        type: writer
        marks:
          - bold
          - italic
          - link
        headings:
          - 2
          - 3
          - 4
          - 5
          - 6
      listOfDetails_about:
        label: Détails
        type: structure
        fields:
          name:
            label: Nom
            type: writer
            help: Colonne de gauche
            marks:
              - bold
              - italic
              - link
            nodes: false
          value:
            label: Valeur
            type: writer
            help: Colonne de droite
            marks:
              - bold
              - italic
              - link
            nodes: false

      mapImage_about:
        type: files
        required: true
        label: Image pied de page
        extends: fields/imageOnlyOne
        layout: cards
        image:
          cover: false
          back: white


  contact:
    icon: map
    label: Contact
    fields:
      textContact:
        label: Texte
        type: writer
        marks:
          - bold
          - italic
          - link
        headings:
          - 2
          - 3
          - 4
          - 5
          - 6

      listOfDetails_contact:
        label: Détails
        type: structure
        fields:
          name:
            label: Nom
            type: writer
            help: Colonne de gauche
            marks:
              - bold
              - italic
              - link
            nodes: false
          value:
            label: Valeur
            type: writer
            help: Colonne de droite
            marks:
              - bold
              - italic
              - link
            nodes: false

      mapImage:
        type: files
        required: true
        label: Image footer
        extends: fields/imageOnlyOne
        layout: cards
        image:
          cover: false
          back: white
