blueprint: page

title: Project

num: date

icon: 📖

status:
  draft:
    label: Brouillon
    text: L'article est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès au panneau.
  unlisted:
    label: En attente de publication
    text: L'article n'est pas encore publiée. L'équipe doit toujours donner le feu vert final pour la publier.
  listed:
    label: Publié
    text: L'article est répertoriée dans l'archive et en ligne.

columns:
  - width: 1/1
    fields:
      arrayOfImagesCarousel:
        type: files
        required: false
        label: Images Home
        help: Image pour le caroussel de la home
        extends: fields/imageMulti
  - width: 1/2
    fields:
      htmlContent:
        label: Texte du projet
        type: writer
        marks:
          - bold
          - italic
          - link
        headings:
          - 2
          - 3
          - 4
          - 5
          - 6
      listOfDetails:
        label: Détails
        type: structure
        fields:
          name:
            label: Nom
            type: writer
            help: Colonne de gauche
            marks:
              - bold
              - italic
              - link
            nodes: false
          value:
            label: Valeur
            type: writer
            help: Colonne de droite
            marks:
              - bold
              - italic
              - link
            nodes: false
      galleryProject:
        type: blocks
        label: Liste des vidéos et images dans la page
        fieldsets:
          - image
          - video
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          imageCover:
            type: files
            required: true
            label: Image couverture projet
            help: Image de couverture pour la page du projet
            extends: fields/imageOnlyOne
            layout: cards
            image:
              cover: false
              back: white
          imageCoverForIndex:
            type: files
            required: true
            label: Image couverture index
            help: Image de couverture pour l'apperçu des images au survole de la souris dans l'index
            extends: fields/imageOnlyOne
          date:
            required: false
            label: Date
            help: Si il n'y a pas de date, le projet sera affiché "Ongoing"
            type: date
            default: false
            display: YYYY-MM
          tags:
            required: true
            label: tags
            type: multiselect
            min: 1
            options:
              type: query
              query: site.find('liste-des-tags').childrenAndDrafts.template('tag')
              text: "{{ item.title }}"
              value: "{{ item.uuid }}"
          selfInitiated:
            label: Self Initiated
            type: toggle
            default: false
            text:
              - "non"
              - "Self Initiated"
      allImagesUpload:
        label: Toutes les images transférées
        layout: table
        type: files
        sortable: false

